#! /bin/bash
#a script to add, remove, and list available printers and drivers.




function addPrinter {
#1st accept input and format the user supplied string

}
#later we will use the return from the addPrinter function
#to predictively populate the trigger via user. 
